#pragma once

#define PL_DEFAULT_VIEWPORT_WIDTH 1920
#define PL_DEFAULT_VIEWPORT_HEIGHT 1080
#define PL_ALL_VIEWPORT_RECT {0, 0, PL_DEFAULT_VIEWPORT_WIDTH, PL_DEFAULT_VIEWPORT_HEIGHT}
#define PL_DEFAULT_FONT_FOLDER "fonts"
#define PL_DEFAULT_IMAGES_FOLDER "images"
#define PL_DEFAULT_SHADER_FOLDER "shaders"

#define PL_GL_INFO_LOG_MAX_LENGTH 512

#define PL_VERSION_MAJOR 0
#define PL_VERSION_MINOR 2
#define PL_VERSION_PATCH 0
