

#define PL_VERSION_MAJOR 0
#define PL_VERSION_MINOR 3
#define PL_VERSION_PATCH 0

#define PL_DEFAULT_IMAGE_FOLDER_PATH std::string("images/")
#define PL_DEFAULT_FONT_FOLDER_PATH std::string("fonts/")

#define PL_DEFAULT_VIEWPORT_WIDTH 1920
#define PL_DEFAULT_VIEWPORT_HEIGHT 1080