# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  lib_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  lib_config = release
  Sandbox_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := lib Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

lib:
ifneq (,$(lib_config))
	@echo "==== Building lib ($(lib_config)) ===="
	@${MAKE} --no-print-directory -C . -f lib.make config=$(lib_config)
endif

Sandbox:
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C . -f Sandbox.make config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f lib.make clean
	@${MAKE} --no-print-directory -C . -f Sandbox.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lib"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"